openapi: 3.0.0
info:
  title: TestVar - Flashcards API
  description: A revolutionary REST API for flashcards
  version: 1.0.1
servers:
  - url: http://localhost:8000/api
    description: Development server
paths:
  /flashcards/{cardId}/hide:
    post:
      summary: "Hide a flashcard by ID"
      tags:
        - "Flashcards"
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Flashcard marked as hidden"
        "403":
          description: "Forbidden"
        "404":
          description: "Flashcard not found"
  /flashcards/{cardId}/unhide:
    post:
      summary: "Unhide a flashcard by ID"
      tags:
        - "Flashcards"
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Flashcard unhidden"
        "403":
          description: "Forbidden"
        "404":
          description: "Flashcard not found"
  /sets/{setId}/rate:
    post:
      summary: "Rate a flashcard set"
      tags:
        - "Flashcard Sets"
      parameters:
        - name: setId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
                  description: "Rating value between 1 and 5"
      responses:
        "200":
          description: "Flashcard set rated successfully"
        "400":
          description: "Invalid rating value"
        "404":
          description: "Flashcard set not found"
  /sets:
    get:
      summary: "Get all flashcard sets"
      tags:
        - "Flashcard Sets"
      responses:
        "200":
          description: "List of flashcard sets"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlashcardSet"
    post:
      summary: "Create a new flashcard set"
      tags:
        - "Flashcard Sets"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlashcardSet"
      responses:
        "201":
          description: "The created flashcard set"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlashcardSet"
        "429":
          description: "You have reached the maximum number of flashcard sets allowed today"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sets/{setId}/attempt_quiz:
    post:
      summary: "Record a quiz attempt"
      tags:
        - "Flashcard Sets"
      parameters:
        - name: setId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_time:
                  type: string
                  format: date-time
                  description: "Quiz start time in ISO format"
                end_time:
                  type: string
                  format: date-time
                  description: "Quiz end time in ISO format"
      responses:
        "200":
          description: "Quiz attempt recorded"
        "400":
          description: "Invalid time format"
        "404":
          description: "Flashcard set not found"
  /users/{userId}/sets:
    get:
      summary: "Get all flashcard sets created by a user"
      tags:
        - "Users"
        - "Flashcard Sets"
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "A list of flashcard sets"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlashcardSet"
        "404":
          description: "The user was not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  # Additional paths for Collections and Users as needed
components:
  schemas:
    FlashcardSet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        rating:
          type: float
          example: 4.5
        user:
          type: string
    Flashcard:
      type: object
      properties:
        id:
          type: integer
        question:
          type: string
        answer:
          type: string
        difficulty:
          type: string
          enum:
            - "easy"
            - "medium"
            - "hard"
        hidden:
          type: boolean
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        is_admin:
          type: boolean
    Error:
      type: object
      properties:
        message:
          type: string
