# Generated by Django 5.1.3 on 2024-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
